id: 1c444fc6-9f80-47a0-9435-d9a2671ab5fc
title: Lister les applications installées via Winget
description: Affiche la liste de toutes les applications installées et gérées par Winget.
category: "\U0001F4E6 Package Management"
platform: Windows
level: Info
tags:
- winget
- package
- list
- inventory
- windows
windowsTemplateId: 4f83ac29-5f18-4b19-9641-b076c6989f65
examples: []
windowsExamples: []
linuxExamples: []
notes: Affiche toutes les applications, même celles non installées via Winget.
links:
- title: Winget list documentation
  url: https://learn.microsoft.com/en-us/windows/package-manager/winget/list
isUserCreated: false
