id: efe266ac-c9b2-4a97-8c0a-9d71b4fbe7ed
name: ansible-playbook
platform: Windows
commandPattern: ansible-playbook {playbookPath} -i {inventory} --limit "{hostPattern}"
parameters:
- name: playbookPath
  label: Chemin du playbook
  type: string
  defaultValue: site.yml
  required: true
  description: Chemin vers le fichier playbook YAML
- name: inventory
  label: Inventaire
  type: string
  defaultValue: inventory.ini
  required: true
  description: Fichier d'inventaire des hôtes
- name: hostPattern
  label: Pattern d'hôtes
  type: string
  defaultValue: webservers
  required: true
  description: Pattern pour limiter les hôtes ciblés
